version: "3.9"

services:
  world-politics-fetcher:
    build: .
    container_name: genesis_fetcher_world_politics
    environment:
      NEWSAPI_KEY: ${NEWSAPI_KEY}
    volumes:
      - ../../data:/data
    restart: "no"
